cask "android-platform-tools"
cask "android-file-transfer"

brew "ccache"
brew "cocoapods"

# special: dcm requires its own tap; trust it so non-interactive bootstrap isn't blocked
tap "CQLabs/dcm", trusted: true
brew "dcm"
